### ISSUE TITLE
[FEAT] Improve meta tags for SEO

### ISSUE THREAD

**Issue by corneliusroemer** [pathoplexus/pathoplexus#107]
Right now our pages don't contain good meta tags, causing google to show just "Pathoplexus: Home" for various pages. We should fix this eventually.

<img width="808" alt="Google Chrome 2024-09-05 13 36 47" src="https://github.com/user-attachments/assets/7528f6fb-f5f7-4464-b963-fc2dd8e6aac7">

**Comment by theosanderson** [comment]
We do need better meta tags, to have a description, but I think in terms of the titles, that was probably fixed by "https://github.com/loculus-project/loculus/pull/2640/files" (unless you are unhappy with that title). I think titles should come from `<title>` tags - but when these were as basic as `Home` Google felt the need to add something to them.

**Comment by corneliusroemer** [comment]
Improved but not fixed - ": Home" isn't great in my view (not terrible but not ideal)

**Comment by theosanderson** [comment]
As I say, I think that's from before that change

**Comment by theosanderson** [comment]
I think when indexed the title was just `Home` and Google has automatically amended that to `Pathoplexus: Home` because otherwise half of its titles would be `Home`
